name: TODO
description: Create a new task or note for something that needs to be done.
title: "[TODO] - <short summary of the task>"
labels: ["todo"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: A concise title for the task.
      placeholder: "Fix mobile navbar bug"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A detailed explanation of the task. Include context, screenshots, or references if applicable.
      placeholder: "The navbar does not collapse properly on iOS devices..."
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What type of task is this?
      options:
        - Bug
        - Feature
        - Improvement
        - Chore
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent or important is this?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: input
    id: related
    attributes:
      label: Related Issues or PRs
      description: Reference related issues or pull requests, if any.
      placeholder: "#45, #102"

  - type: textarea
    id: steps
    attributes:
      label: Steps to Complete
      description: Break down the task into actionable steps or checklist.
      placeholder: |
        - [ ] Investigate bug behavior on iOS
        - [ ] Write failing test case
        - [ ] Fix the bug
        - [ ] Write documentation
      render: markdown

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any extra information, considerations, or questions.
